development:
  adapter: postgresql
  encoding: UTF-8
  database: marketify
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: UTF-8
  database: marketify
  pool: 5
  username: postgres
  password: postgres